### ISSUE TITLE
Color code issue.

### ISSUE THREAD

**Issue by EnderSlime123** [TheBusyBiscuit/ChestTerminal#11]
I reported this through Discord but you yelled at me. Anyways...

![2019-04-19_08 41 49](https://user-images.githubusercontent.com/47653006/56431734-b47d7400-627f-11e9-9d52-0db644a40fc7.png)

Color codes for ChestTerminal's messages are still bugged. Apart from that, it works fine.

**Comment by TheBusyBiscuit** [comment]
I did not yell at you, I told you to make a proper Issue with versions and a server log...
