### ISSUE TITLE
Access Terminal No item cached

### ISSUE THREAD

**Issue by Redemption198** [TheBusyBiscuit/ChestTerminal#2]
When I click on the access terminal it shows only barrier blocks named "No item cached", I don't know what am I missing, I've set the chests and the nodes (with CT channel) as in the videos on your YouTube channel.
I don't know if it's a bug or is something that I forgot to do.

**Comment by TheBusyBiscuit** [comment]
Definitely something you forgot to do...
Empty Blacklist, CT Channel, Cargo Manager, Access Terminal...
