### ISSUE TITLE
Major bug making items disappear, and so making the addon useless.

### ISSUE THREAD

**Issue by jobogamer24** [TheBusyBiscuit/ChestTerminal#25]
The addon "chest terminal" is working fine until you try to remove a stack from the access terminal. When you remove items one by one with the left click, you can perfectly take it from the system, but when you try to right click an item, it just suppress it. Also if you have less than a stack of the same item, if you try to remove them by left clicking, while reaching the last one it will disappear from the slot.

https://s.jordanj.fr/5xaibwUALt.gif

It should work this way: Right clicking on an item should add a stack of it in the bottom right slot, while not suppressing it.

 - Minecraft Version: Paper 1.15.2 (Build 216)
 - CS-CoreLib Version: vDEV 85
 - Slimefun Version: vRC 11
 - ChestTerminal Version: vDEV 30

**Comment by SchlafiTobs** [comment]
Have you checked the amount of items disappearing? It seems like the system eats up more than 64 Items even if you can only request 64. Need a confirmation if that's only on our end or global.

**Comment by jobogamer24** [comment]
I don't really understand your question, I know that other users have reported the problem on Discord.
I remain at your disposal for any further questions.

**Comment by MrWardy** [comment]
@SchlafiTobs I think I understand your question, as I'm having the same issue, not only with removing an entire stack of an item but also with removing unstackable items. When I was testing it, the system only seemed to eat up the stack I request, so if I have 128 items in there and request an entire stack, it will eat up that stack but I still have 64 remaining items in the system. The same thing happens with unstackable items, if I request just one of those items providing I have multiple in the system, it will eat up just the one item I request, and not all of them.

**Comment by NCBPFluffyBear** [comment]
Im having this problem too, here's to clarify:

Removing anything using Right-Click to remove all items causes the item to disappear from the panel and the chest (It gets deleted). This happens when following the design showcased in [this](https://www.youtube.com/watch?v=80tXQ9V8qIw) video.

**Comment by houbou98-19** [comment]
Im having this problem too and i discovered another thing with it while trying to figure out what the problem might be. left clicking until you get 63 works just fine. however, as soon as you left click to make it 64 (a full stack, as if you right clicked) the items get deleted

**Comment by Hellcode48** [comment]
Getting same problem
