### ISSUE TITLE
Duping items with explosive pickaxe

### ISSUE THREAD

**Issue by Volgeop** [TheBusyBiscuit/ChestTerminal#31]
## Description (Required)

Hi, when you mine blocks next to for ex. CT Access Terminal, then you can dupe items...

## Steps to reproduce the Issue (Required)
https://streamable.com/mtnhuo (video used for Barrels plugin with same bug, but chest terminal has same issue, like barrels and private storage)

## Expected behavior (Required)

This shouldn't happen....

## Environment (Required)

 - Minecraft Version: 1.16.2
 - CS-CoreLib Version: 88
 - Slimefun Version: 671
 - ChestTerminal Version: 35

**Comment by TheBusyBiscuit** [comment]
Don't provide videos which have nothing to do with what you are reporting.

**Comment by Volgeop** [comment]
But it's same principe.... Just mine with explosive pickaxe next to this item.
