### ISSUE TITLE
Chest Terminal Issue with arrow heads

### ISSUE THREAD

**Issue by Mood-Lore** [TheBusyBiscuit/ChestTerminal#32]
## Description (Required)
 When placing down a chest terminal and right clicking it to open it and clicking an arrow head(the things that can go from previous and next page). I get given the arrow heads instead of being transferred to the previous or next page.

## Steps to reproduce the Issue (Required)
 https://youtu.be/39K5bWuLLMg

## Expected behavior (Required)
 Ehm, I was expecting it to go to the previous/next page.

## Server Log / Error Report
https://pastebin.com/Hkg52x72

## Environment (Required)

 - Minecraft Version: v1_16_R2
 - CS-CoreLib Version: vDEV - 91 (git e42a05d1)
 - Slimefun Version: vDEV - 676 (git 07f5687b)
 - ChestTerminal Version: vDEV - 35 (git 2ae809d7)

**Comment by TheBusyBiscuit** [comment]
The error seems to lie within Slimefun's cargo network code actually, so this should be fixed in the next Slimefun build.
