### ISSUE TITLE
Error spamming causing TPS Lag

### ISSUE THREAD

**Issue by Nullsify** [TheBusyBiscuit/ChestTerminal#33]
## Description (Required)

This weird error has spammed the console, making the server's TPS drop drastically
## Steps to reproduce the Issue (Required)

Place a chest terminal.
## Expected behavior (Required)

Not to lag the server.
## Server Log / Error Report

https://pastebin.com/jZaZX1AA
[latest.log](https://github.com/TheBusyBiscuit/ChestTerminal/files/5244068/latest.log)

## Environment (Required)

![unknown](https://user-images.githubusercontent.com/62045977/93570328-6d8c3480-f9c5-11ea-975a-11d65c7a3473.png)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - ChestTerminal Version:

**Comment by TheBusyBiscuit** [comment]
The error seems to lie within Slimefun's cargo network code actually, so this should be fixed in the next Slimefun build.
