### ISSUE TITLE
Duping items with Explosive pickaxe

### ISSUE THREAD

**Issue by bobhenl** [TheBusyBiscuit/ChestTerminal#34]
## Description (Required)

Hi, when you mine blocks next to for ex. CT Access Terminal, then you can dupe items...

## Steps to reproduce the Issue (Required)
Isn't needed, just try use Explosive pickaxe with CT Access Terminal.  Please, don't lock and try it on your own.

## Expected behavior (Required)

This shouldn't happen....

## Environment (Required)

 - Minecraft Version: 1.16.2
 - CS-CoreLib Version: 88
 - Slimefun Version: 671
 - ChestTerminal Version: 35

**Comment by Volgeop** [comment]
Hopefully get fixed soon

**Comment by bobhenl** [comment]
Is additional information needed @TheBusyBiscuit ? I think that dupe bug is important... Can't use plugin few months due to this, cause players can simply google it. And you fixed it in another plugins, so where's the problem? I see that you fix another issues, but the most important - duping one is still here, or do you wanna tell me that these https://github.com/TheBusyBiscuit/ChestTerminal/issues/36, or this? https://github.com/TheBusyBiscuit/ChestTerminal/issues/45 https://github.com/TheBusyBiscuit/ChestTerminal/issues/37 https://github.com/TheBusyBiscuit/ChestTerminal/issues/40

-> You're fixing issues with specific things, but DUPE issue that is one of the most important still isn't fixed, why? I really don't understand it. Do you need more context? I think it's nott needed, cause similar issue happened to more plugins where you fixed it. Wanna use it again after few months, but I still can't. And everytime I see you update it without fixing this dupe thing, I'm really confused why you choosed these issues before this one.

**Comment by bobhenl** [comment]
Magically fixed.
