### ISSUE TITLE
Problem opening CT buses

### ISSUE THREAD

**Issue by NCBPFluffyBear** [TheBusyBiscuit/ChestTerminal#35]
## Description (Required)
Right clicking CT buses does nothing, and an error appears in console.

## Steps to reproduce the Issue (Required)
1. Get a CT bus (Inputs and outputs both work)
2. Place the bus and interact with it

## Expected behavior (Required)
Bus should be openable

## Server Log / Error Report
https://hastebin.com/webiduwesi.sql

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - ChestTerminal Version:
![image](https://user-images.githubusercontent.com/31554056/93687102-b5bc5d00-fa80-11ea-8228-78665a6d1c18.png)

**Comment by TheBusyBiscuit** [comment]
The hastebin link is empty.
