### ISSUE TITLE
CT Import/Export Bus not showing GUI.

### ISSUE THREAD

**Issue by Nullsify** [TheBusyBiscuit/ChestTerminal#37]
## Description (Required)

Whenever trying to access the GUI for the buses, they don't and just throw an error in the console.
## Steps to reproduce the Issue (Required)

Placing a CT import or export bus and trying to interact with it
## Expected behavior (Required)

GUI should pop up normally
## Server Log / Error Report

https://pastebin.com/FK3Tfzjy
## Environment (Required)

![unknown](https://user-images.githubusercontent.com/62045977/93809816-56c53680-fc80-11ea-8929-f5038d642944.png)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - ChestTerminal Version:

**Comment by Seggan** [comment]
I have same problem
