### ISSUE TITLE
[Feature Request] Search in CT

### ISSUE THREAD

**Issue by D1yt** [TheBusyBiscuit/ChestTerminal#41]
How about adding a search button to the CT terminal to find items via chat message?
This should be relatively easy, I'll look into it myself in a few months xD

**Comment by TheBusyBiscuit** [comment]
Please only use the bug tracker to report bugs.

**Comment by D1yt** [comment]
I'm sorry but I can't join the discord so please just let me suggest stuff over here.

I don't want to be annoying, but I have no other way to share my ideas.
