### ISSUE TITLE
Spigot 1.12.1 Dupe Issue

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/ChestTerminal#5]
It seems like ChestTerminal has a fatal issue where if you put a item in the terminal, it wont go into the system and it will dupe when taking it out, also nothing shows in the system either, no errors

**Comment by neoneosa** [comment]
This plugin has been abandoned, so this wont get fixed unless you do it yourself and make a Pull Request with the fix.

**Comment by xH3LLRAIZ3Rx** [comment]
Actually fixed in latest slimefun (compiled)
